### ISSUE TITLE
Build failure on GHC 9.8.1: 'Illegal invisible type variable binder'

### ISSUE THREAD

**Issue by Vekhir** [dhall-lang/dhall-haskell#2567]
Hi,
when building `dhall` 1.42.1 on Arch Linux with GHC 9.8.1 and `template-haskell` 2.21.0.0, the following error occurs while building the tests:

```
tests/Dhall/Test/TH.hs:111:1: error: [GHC-58589]
    Illegal invisible type variable binder: @b0
    Suggested fix: Perhaps you intended to use TypeAbstractions
    |
111 | Dhall.TH.makeHaskellTypesWith (Dhall.TH.defaultGenerateOptions
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
The same error occurs 4 times (see Appendix). The error itself suggests to use TypeAbstractions to fix the issue.\
The offending line is [dhall/tests/Dhall/Test/TH.hs#L111](https://github.com/dhall-lang/dhall-haskell/blob/main/dhall/tests/Dhall/Test/TH.hs#L111), and the issue doesn't seem fixed on `main`.

`template-haskell` from 2.21 onwards supports Invisible binders in type declarations, see also [the migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.8#invisible-binders-in-type-level-declarations) and [ GHC proposal #425](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0425-decl-invis-binders.rst).\
`dhall` 1.42.1 advertises support for `template-haskell` 2.21 and GHC 9.8 - not sure what's going on there.

-- Vekhir

## Appendix
```
[ 5 of 21] Compiling Dhall.Test.TH    ( tests/Dhall/Test/TH.hs, dist/build/tasty/tasty-tmp/Dhall/Test/TH.dyn_o )

tests/Dhall/Test/TH.hs:111:1: error: [GHC-58589]
    Illegal invisible type variable binder: @a0
    Suggested fix: Perhaps you intended to use TypeAbstractions
    |
111 | Dhall.TH.makeHaskellTypesWith (Dhall.TH.defaultGenerateOptions
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

tests/Dhall/Test/TH.hs:111:1: error: [GHC-58589]
    Illegal invisible type variable binder: @a1
    Suggested fix: Perhaps you intended to use TypeAbstractions
    |
111 | Dhall.TH.makeHaskellTypesWith (Dhall.TH.defaultGenerateOptions
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

tests/Dhall/Test/TH.hs:111:1: error: [GHC-58589]
    Illegal invisible type variable binder: @b0
    Suggested fix: Perhaps you intended to use TypeAbstractions
    |
111 | Dhall.TH.makeHaskellTypesWith (Dhall.TH.defaultGenerateOptions
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

tests/Dhall/Test/TH.hs:111:1: error: [GHC-58589]
    Illegal invisible type variable binder: @a0
    Suggested fix: Perhaps you intended to use TypeAbstractions
    |
111 | Dhall.TH.makeHaskellTypesWith (Dhall.TH.defaultGenerateOptions
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by ysangkok** [comment]
Does the code merged in 

* https://github.com/dhall-lang/dhall-haskell/pull/2602 

fix your issue?

**Comment by ysangkok** [comment]
Oh, seems that it doesn't , I am able to reproduce with

```
cabal test --enable-tests --allow-newer=special-values:bytestring -w ghc-9.8.4`
```

**Comment by ysangkok** [comment]
It's weird how it fails on GHC-9.8 when @TeofilC says in #2602 that they tested with GHC-9.10. I wonder if it's a bug fixed in GHC 9.10 somehow?

**Comment by TeofilC** [comment]
I think I might've missed these because I didn't pass `--enable-tests`, cabal-install didn't find a build plan and just skipped them. After enabling that flag I am also seeing these with 9.10

**Comment by TeofilC** [comment]
It looks like enabling `TypeAbstractions` doesn't fix this (at least with 9.10). I'll take a further look

**Comment by TeofilC** [comment]
For reference here's the error we get if we enable TypeAbstractions and the generated TH splice
<details><summary>Details</summary>
<p>

```
tests/Dhall/Test/TH.hs:114:1: error: [GHC-92337]
    • Invalid invisible type variable binder: @a0
      Either a standalone kind signature (SAKS)
      or a complete user-supplied kind (CUSK, legacy feature)
      is required to use invisible binders.
    • In the data type declaration for ‘MyHKSingle’
    Suggested fix: Add a standalone kind signature for ‘MyHKSingle’
    |
114 | Dhall.TH.makeHaskellTypesWith (Dhall.TH.defaultGenerateOptions
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...


```

```
tests/Dhall/Test/TH.hs:(114,1)-(122,5): Splicing declarations
    Dhall.TH.makeHaskellTypesWith
      (Dhall.TH.defaultGenerateOptions
         {Dhall.TH.constructorModifier = ("My" <>),
          Dhall.TH.fieldModifier = ("my" <>) . Data.Text.toTitle,
          Dhall.TH.generateFromDhallInstance = False,
          Dhall.TH.generateToDhallInstance = False})
      [SingleConstructor
         "MyHKSingle" "HKSingle" "./tests/th/HigherKindSingle.dhall",
       MultipleConstructors
         "MyHKUnion" "./tests/th/HigherKindUnion.dhall"]
  ======>
    data MyHKSingle @a1 @a0
      = MyHKSingle {myBam :: Dhall.Text, myBar :: (a1 a0), myFoo :: a0}
    data MyHKUnion @a0 @b0 = MyBar b0 | MyFoo a0
```

</p>
</details>

**Comment by TeofilC** [comment]
https://github.com/dhall-lang/dhall-haskell/pull/2622 should fix this by restoring the TH generated code to what it was before GHC-9.8
